version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend/namibia

  backend:
    build:
      context: ./backend/namibia
    # Include volume for local configs
    volumes:
      - ./distro/configuration:/openmrs/distribution/openmrs_configz
